Traceback (most recent call last):
  File "/home/bryan/main/Empresas/UTP/Proyectos/MCP-UTP/servers/social_networks.py", line 6, in <module>
    from fastmcp import FastMCP
ModuleNotFoundError: No module named 'fastmcp'
